/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as fiscalAttestationsIndexImport } from './routes/(fiscal-attestations)/index'
import { Route as fiscalAttestationsFiscalATIdIndexImport } from './routes/(fiscal-attestations)/$fiscalATId/index'
import { Route as fiscalAttestationsFiscalATIdViewIndexImport } from './routes/(fiscal-attestations)/$fiscalATId/view/index'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const fiscalAttestationsIndexRoute = fiscalAttestationsIndexImport.update({
  id: '/(fiscal-attestations)/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const fiscalAttestationsFiscalATIdIndexRoute =
  fiscalAttestationsFiscalATIdIndexImport.update({
    id: '/(fiscal-attestations)/$fiscalATId/',
    path: '/$fiscalATId/',
    getParentRoute: () => rootRoute,
  } as any)

const fiscalAttestationsFiscalATIdViewIndexRoute =
  fiscalAttestationsFiscalATIdViewIndexImport.update({
    id: '/(fiscal-attestations)/$fiscalATId/view/',
    path: '/$fiscalATId/view/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/(fiscal-attestations)/': {
      id: '/(fiscal-attestations)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof fiscalAttestationsIndexImport
      parentRoute: typeof rootRoute
    }
    '/(fiscal-attestations)/$fiscalATId/': {
      id: '/(fiscal-attestations)/$fiscalATId/'
      path: '/$fiscalATId'
      fullPath: '/$fiscalATId'
      preLoaderRoute: typeof fiscalAttestationsFiscalATIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/(fiscal-attestations)/$fiscalATId/view/': {
      id: '/(fiscal-attestations)/$fiscalATId/view/'
      path: '/$fiscalATId/view'
      fullPath: '/$fiscalATId/view'
      preLoaderRoute: typeof fiscalAttestationsFiscalATIdViewIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/': typeof fiscalAttestationsIndexRoute
  '/$fiscalATId': typeof fiscalAttestationsFiscalATIdIndexRoute
  '/$fiscalATId/view': typeof fiscalAttestationsFiscalATIdViewIndexRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/': typeof fiscalAttestationsIndexRoute
  '/$fiscalATId': typeof fiscalAttestationsFiscalATIdIndexRoute
  '/$fiscalATId/view': typeof fiscalAttestationsFiscalATIdViewIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/about': typeof AboutRoute
  '/(fiscal-attestations)/': typeof fiscalAttestationsIndexRoute
  '/(fiscal-attestations)/$fiscalATId/': typeof fiscalAttestationsFiscalATIdIndexRoute
  '/(fiscal-attestations)/$fiscalATId/view/': typeof fiscalAttestationsFiscalATIdViewIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/' | '/$fiscalATId' | '/$fiscalATId/view'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/' | '/$fiscalATId' | '/$fiscalATId/view'
  id:
    | '__root__'
    | '/about'
    | '/(fiscal-attestations)/'
    | '/(fiscal-attestations)/$fiscalATId/'
    | '/(fiscal-attestations)/$fiscalATId/view/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  fiscalAttestationsIndexRoute: typeof fiscalAttestationsIndexRoute
  fiscalAttestationsFiscalATIdIndexRoute: typeof fiscalAttestationsFiscalATIdIndexRoute
  fiscalAttestationsFiscalATIdViewIndexRoute: typeof fiscalAttestationsFiscalATIdViewIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  fiscalAttestationsIndexRoute: fiscalAttestationsIndexRoute,
  fiscalAttestationsFiscalATIdIndexRoute:
    fiscalAttestationsFiscalATIdIndexRoute,
  fiscalAttestationsFiscalATIdViewIndexRoute:
    fiscalAttestationsFiscalATIdViewIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/about",
        "/(fiscal-attestations)/",
        "/(fiscal-attestations)/$fiscalATId/",
        "/(fiscal-attestations)/$fiscalATId/view/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/(fiscal-attestations)/": {
      "filePath": "(fiscal-attestations)/index.tsx"
    },
    "/(fiscal-attestations)/$fiscalATId/": {
      "filePath": "(fiscal-attestations)/$fiscalATId/index.tsx"
    },
    "/(fiscal-attestations)/$fiscalATId/view/": {
      "filePath": "(fiscal-attestations)/$fiscalATId/view/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
